List dailyTasks = [
  {
    "guid": "35757089-ECDD-1F8D-BCE6-E8B98E8C58BD",
    "name": "Paying  bills",
    "phone": "1-544-580-1018",
    "time": "1:21 PM",
    "category": "Market",
    "Priority": "important",
    "isFavorite": true,
    "publisherName": "Hamish Atkins",
    "publisherGender": "Male",
    "phone1": "1-288-645-4838",
    "country": "Australia",
    "date": "2022-08-22 06:06:09",
    "description":
        "est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam",
    "item_type": "Task",
    "address": "Ap #680-6672 Feugiat Ave",
    "location": "P.O. Box 412, 1492 Leo, Road",
    "conatct_name": "Odysseus Puckett",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=20",
    "image": "https://source.unsplash.com/random/200x200?sig=1"
  },
  {
    "guid": "D04BA8BD-1A48-BCB9-5BC1-6535D8D383EC",
    "name": "Scheduling  appointments",
    "phone": "(578) 344-6593",
    "time": "2:22 AM",
    "category": "Fitness",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Julie Sims",
    "publisherGender": "Male",
    "phone1": "1-471-584-3774",
    "country": "Costa Rica",
    "date": "2022-08-11 23:02:59",
    "description":
        "elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue",
    "item_type": "Task",
    "address": "P.O. Box 466, 310 Nulla Rd.",
    "location": "Ap #322-8313 Non, Avenue",
    "conatct_name": "Octavia Mcdowell",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=7",
    "image": "https://source.unsplash.com/random/200x200?sig=15"
  },
  {
    "guid": "9899D857-D62E-C69F-BD99-D52A5D9234BC",
    "name": "Party planning",
    "phone": "1-875-611-3526",
    "time": "1:07 PM",
    "category": "Friend",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Mara Ortega",
    "publisherGender": "Male",
    "phone1": "1-913-313-2358",
    "country": "Austria",
    "date": "2022-07-28 09:33:23",
    "description":
        "elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut",
    "item_type": "Task",
    "address": "Ap #568-3024 Quisque St.",
    "location": "Ap #229-8066 Etiam Av.",
    "conatct_name": "Abdul Wiggins",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=11",
    "image": "https://source.unsplash.com/random/200x200?sig=12"
  },
  {
    "guid": "A5C3A55D-9DDE-B994-ADAE-69DA52799870",
    "name": "Scheduling  appointments",
    "phone": "(967) 265-2754",
    "time": "12:31 PM",
    "category": "Friend",
    "Priority": "blue",
    "isFavorite": true,
    "publisherName": "Carlos Howe",
    "publisherGender": "Male",
    "phone1": "(691) 742-6188",
    "country": "Australia",
    "date": "2022-08-30 02:20:28",
    "description":
        "placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus.",
    "item_type": "Task",
    "address": "4989 Elit Rd.",
    "location": "882-8359 Leo Road",
    "conatct_name": "Rose Gates",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=20",
    "image": "https://source.unsplash.com/random/200x200?sig=12"
  },
  {
    "guid": "8ADC0C2B-141D-DD35-E9AD-7BB1722C9125",
    "name": "Scheduling appointments",
    "phone": "(100) 412-6495",
    "time": "6:22 AM",
    "category": "Offical",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Leonard King",
    "publisherGender": "Male",
    "phone1": "1-385-446-7783",
    "country": "Turkey",
    "date": "2022-08-04 06:48:08",
    "description":
        "sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem",
    "item_type": "Task",
    "address": "7494 Aenean Rd.",
    "location": "Ap #902-6501 Gravida Road",
    "conatct_name": "Judith Huber",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=12",
    "image": "https://source.unsplash.com/random/200x200?sig=13"
  },
  {
    "guid": "24A2CB33-A1B3-55E8-8D2A-BC246586B1BA",
    "name": "Light garden care",
    "phone": "(272) 612-2911",
    "time": "9:01 PM",
    "category": "Market",
    "Priority": "important",
    "isFavorite": false,
    "publisherName": "Ebony Madden",
    "publisherGender": "Male",
    "phone1": "1-641-478-4453",
    "country": "Belgium",
    "date": "2022-08-09 17:41:59",
    "description":
        "ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In",
    "item_type": "Task",
    "address": "5763 In Rd.",
    "location": "2391 Proin Avenue",
    "conatct_name": "Brett Jimenez",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=9",
    "image": "https://source.unsplash.com/random/200x200?sig=15"
  },
  {
    "guid": "767D6BA1-98E5-982E-C12D-A44875314488",
    "name": "Errands",
    "phone": "1-671-712-7832",
    "time": "3:35 PM",
    "category": "Offical",
    "Priority": "important",
    "isFavorite": true,
    "publisherName": "Kylee Vaughn",
    "publisherGender": "Male",
    "phone1": "(683) 979-6960",
    "country": "Poland",
    "date": "2022-07-29 04:05:49",
    "description":
        "nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris.",
    "item_type": "Task",
    "address": "Ap #666-8683 Ultrices Av.",
    "location": "364-7110 Magnis Street",
    "conatct_name": "Sonya Benson",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=10",
    "image": "https://source.unsplash.com/random/200x200?sig=8"
  },
  {
    "guid": "9BA1B6CE-DBFC-5B92-23A6-07F0A2C90098",
    "name": "Paying bills",
    "phone": "1-235-267-3811",
    "time": "8:11 AM",
    "category": "Health",
    "Priority": "blue",
    "isFavorite": true,
    "publisherName": "Kalia Garner",
    "publisherGender": "Male",
    "phone1": "1-644-195-8168",
    "country": "Colombia",
    "date": "2022-08-27 20:00:00",
    "description":
        "enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit",
    "item_type": "Task",
    "address": "799-2286 Dictum Av.",
    "location": "507-5572 Scelerisque Street",
    "conatct_name": "Zane Faulkner",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=19",
    "image": "https://source.unsplash.com/random/200x200?sig=5"
  },
  {
    "guid": "F25A979F-EBA4-D0F2-9E52-B20F21DDA577",
    "name": "Making travel arrangements",
    "phone": "1-738-261-7859",
    "time": "9:37 AM",
    "category": "Market",
    "Priority": "blue",
    "isFavorite": true,
    "publisherName": "Michael Sharpe",
    "publisherGender": "Male",
    "phone1": "1-689-530-3395",
    "country": "Netherlands",
    "date": "2022-08-10 09:37:35",
    "description": "dolor. Fusce feugiat. Lorem ipsum dolor sit amet,",
    "item_type": "Task",
    "address": "804-2866 A Street",
    "location": "Ap #760-9926 Nisi Av.",
    "conatct_name": "Cain Garner",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=20",
    "image": "https://source.unsplash.com/random/200x200?sig=14"
  },
  {
    "guid": "CBABCE07-A694-E693-A1BE-B84922F34605",
    "name": "Grocery shopping",
    "phone": "1-954-835-4135",
    "time": "10:44 AM",
    "category": "Market",
    "Priority": "important",
    "isFavorite": false,
    "publisherName": "Germaine Mcclain",
    "publisherGender": "Male",
    "phone1": "1-826-435-0848",
    "country": "Ukraine",
    "date": "2022-07-27 23:01:37",
    "description": "at arcu. Vestibulum ante ipsum primis in",
    "item_type": "Task",
    "address": "530-6865 Massa. St.",
    "location": "529-7990 Habitant Rd.",
    "conatct_name": "Clementine Moreno",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=20",
    "image": "https://source.unsplash.com/random/200x200?sig=12"
  },
  {
    "guid": "A747C8A9-BBAB-348C-C2DF-CE0C77647D1F",
    "name": "clothes,",
    "phone": "(546) 475-7016",
    "time": "6:44 PM",
    "category": "Friend",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Whilemina Spears",
    "publisherGender": "Male",
    "phone1": "(371) 777-1438",
    "country": "Pakistan",
    "date": "2022-08-29 21:11:33",
    "description":
        "convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem",
    "item_type": "Task",
    "address": "408-5386 Rutrum St.",
    "location": "Ap #801-1741 Proin St.",
    "conatct_name": "Vaughan Olson",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=1",
    "image": "https://source.unsplash.com/random/200x200?sig=5"
  },
  {
    "guid": "A5F4142A-4E63-E376-3269-7361131B2E78",
    "name": "clothes,",
    "phone": "1-537-415-6375",
    "time": "8:58 AM",
    "category": "Friend",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Anika Wheeler",
    "publisherGender": "Male",
    "phone1": "1-241-662-2395",
    "country": "New Zealand",
    "date": "2022-08-20 00:59:29",
    "description":
        "ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique",
    "item_type": "Task",
    "address": "284 Nec Rd.",
    "location": "Ap #505-2103 Amet, Ave",
    "conatct_name": "Mercedes Valencia",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=20",
    "image": "https://source.unsplash.com/random/200x200?sig=5"
  },
  {
    "guid": "B19BC2CD-B8AA-7297-BA10-27D792ED29C6",
    "name": "Research",
    "phone": "(633) 427-2351",
    "time": "9:07 AM",
    "category": "Offical",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Preston Wolfe",
    "publisherGender": "Male",
    "phone1": "1-259-685-4876",
    "country": "China",
    "date": "2022-08-15 17:38:20",
    "description":
        "non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam",
    "item_type": "Task",
    "address": "783-2823 Integer Avenue",
    "location": "376-6034 Pellentesque Street",
    "conatct_name": "Cole Carney",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=8",
    "image": "https://source.unsplash.com/random/200x200?sig=18"
  },
  {
    "guid": "976BE679-D72E-41B4-C68A-CF425E3957B0",
    "name": "household,",
    "phone": "(343) 936-5255",
    "time": "4:28 PM",
    "category": "Friend",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Barry Santos",
    "publisherGender": "Male",
    "phone1": "1-453-561-9148",
    "country": "Russian Federation",
    "date": "2022-08-06 07:21:18",
    "description":
        "Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros.",
    "item_type": "Task",
    "address": "9869 Libero. Avenue",
    "location": "Ap #141-9697 Nunc St.",
    "conatct_name": "Kirk Bean",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=17",
    "image": "https://source.unsplash.com/random/200x200?sig=20"
  },
  {
    "guid": "5EAA4964-4CD6-5019-96E5-4BB9D4CE30BB",
    "name": "Transportation_to_appointments",
    "phone": "(553) 488-8856",
    "time": "8:17 AM",
    "category": "Friend",
    "Priority": "important",
    "isFavorite": true,
    "publisherName": "Hayes Barlow",
    "publisherGender": "Male",
    "phone1": "(244) 293-5412",
    "country": "China",
    "date": "2022-08-19 20:36:33",
    "description":
        "aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium",
    "item_type": "Task",
    "address": "P.O. Box 553, 9573 At Rd.",
    "location": "Ap #875-5256 Est Rd.",
    "conatct_name": "Shafira Griffith",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=2",
    "image": "https://source.unsplash.com/random/200x200?sig=1"
  },
  {
    "guid": "B9EEC2AB-0EE1-12C7-3DAC-264BC19D4C5F",
    "name": "Research",
    "phone": "1-255-614-6711",
    "time": "1:51 AM",
    "category": "Friend",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Timothy Roach",
    "publisherGender": "Male",
    "phone1": "1-841-234-2238",
    "country": "Belgium",
    "date": "2022-07-26 01:09:54",
    "description":
        "Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu,",
    "item_type": "Task",
    "address": "1353 Nam Av.",
    "location": "695-596 Elit. Street",
    "conatct_name": "Farrah Blair",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=5",
    "image": "https://source.unsplash.com/random/200x200?sig=9"
  },
  {
    "guid": "E3D1CE62-CD7B-BD7D-4768-D8CBE2B64A61",
    "name": "Light garden care",
    "phone": "(831) 565-1185",
    "time": "5:52 AM",
    "category": "Health",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Elijah Garrison",
    "publisherGender": "Male",
    "phone1": "(618) 720-1432",
    "country": "Pakistan",
    "date": "2022-07-28 22:34:40",
    "description":
        "lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris",
    "item_type": "Task",
    "address": "P.O. Box 404, 458 Rhoncus Rd.",
    "location": "981-672 Ornare Road",
    "conatct_name": "Petra Myers",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=5",
    "image": "https://source.unsplash.com/random/200x200?sig=8"
  },
  {
    "guid": "19891938-7C21-3534-1417-ED08BD530C32",
    "name": "Scheduling",
    "phone": "1-576-555-1614",
    "time": "9:31 PM",
    "category": "Market",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Aurora Watkins",
    "publisherGender": "Male",
    "phone1": "1-541-399-4822",
    "country": "Philippines",
    "date": "2022-07-26 05:09:47",
    "description":
        "ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer",
    "item_type": "Task",
    "address": "Ap #629-4588 Metus. Rd.",
    "location": "P.O. Box 292, 5434 Amet Ave",
    "conatct_name": "Leigh Delaney",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=19",
    "image": "https://source.unsplash.com/random/200x200?sig=4"
  },
  {
    "guid": "06416B57-927D-8639-98CD-BFF75D319364",
    "name": "Grocery shopping",
    "phone": "1-481-502-2075",
    "time": "4:10 AM",
    "category": "Health",
    "Priority": "important",
    "isFavorite": false,
    "publisherName": "Amela Brewer",
    "publisherGender": "Male",
    "phone1": "(380) 716-3497",
    "country": "Italy",
    "date": "2022-08-18 18:32:56",
    "description":
        "dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque",
    "item_type": "Task",
    "address": "P.O. Box 973, 3734 Aliquet Rd.",
    "location": "9430 Molestie Rd.",
    "conatct_name": "Maia Sanchez",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=7",
    "image": "https://source.unsplash.com/random/200x200?sig=12"
  },
  {
    "guid": "B81BC5D3-7916-454B-237A-89C8E780C666",
    "name": "Paying bills",
    "phone": "1-276-294-5568",
    "time": "7:58 PM",
    "category": "Friend",
    "Priority": "blue",
    "isFavorite": true,
    "publisherName": "Devin Williams",
    "publisherGender": "Male",
    "phone1": "(624) 781-2564",
    "country": "Vietnam",
    "date": "2022-08-02 08:44:47",
    "description":
        "volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget",
    "item_type": "Task",
    "address": "447-2200 Ante Street",
    "location": "Ap #524-6208 Mauris Rd.",
    "conatct_name": "Evangeline Walls",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=1",
    "image": "https://source.unsplash.com/random/200x200?sig=5"
  },
  {
    "guid": "DE2528C4-8B83-2CEE-7684-72D78E1966DC",
    "name": "Shopping",
    "phone": "(655) 381-4447",
    "time": "4:18 PM",
    "category": "Market",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Beverly Clarke",
    "publisherGender": "Male",
    "phone1": "1-422-346-7127",
    "country": "Brazil",
    "date": "2022-08-23 05:45:44",
    "description": "ultrices posuere cubilia Curae",
    "item_type": "Task",
    "address": "113-8230 Ornare, Rd.",
    "location": "687-5441 Erat Rd.",
    "conatct_name": "Skyler Scott",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=8",
    "image": "https://source.unsplash.com/random/200x200?sig=11"
  },
  {
    "guid": "84F7B2A5-2676-9647-40D7-4EB69B420A59",
    "name": "Light garden care",
    "phone": "1-579-405-6497",
    "time": "12:31 AM",
    "category": "Offical",
    "Priority": "important",
    "isFavorite": true,
    "publisherName": "Gail Mccarthy",
    "publisherGender": "Male",
    "phone1": "(850) 383-2654",
    "country": "Turkey",
    "date": "2022-08-12 15:46:24",
    "description":
        "gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum.",
    "item_type": "Task",
    "address": "3137 Laoreet, Street",
    "location": "1339 Et Ave",
    "conatct_name": "Ryder West",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=18",
    "image": "https://source.unsplash.com/random/200x200?sig=16"
  },
  {
    "guid": "52977E79-CD5E-D232-38E8-9BC73D3ED4C7",
    "name": "Emails and correspondence",
    "phone": "1-779-986-3468",
    "time": "4:19 PM",
    "category": "Friend",
    "Priority": "blue",
    "isFavorite": true,
    "publisherName": "Isadora Jacobs",
    "publisherGender": "Male",
    "phone1": "1-722-820-2662",
    "country": "Netherlands",
    "date": "2022-08-27 17:26:58",
    "description":
        "luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi",
    "item_type": "Task",
    "address": "3458 Mauris St.",
    "location": "8770 At Road",
    "conatct_name": "Susan Welch",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=8",
    "image": "https://source.unsplash.com/random/200x200?sig=14"
  },
  {
    "guid": "56BDCA9E-9D0C-C577-C453-9FEE4CD07DDC",
    "name": "Light housekeeping",
    "phone": "1-984-875-9134",
    "time": "5:37 AM",
    "category": "Fitness",
    "Priority": "blue",
    "isFavorite": true,
    "publisherName": "Nita Morgan",
    "publisherGender": "Male",
    "phone1": "1-307-822-9582",
    "country": "United States",
    "date": "2022-08-17 17:59:34",
    "description":
        "aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis",
    "item_type": "Task",
    "address": "6168 Sodales Road",
    "location": "442-8015 Elit Avenue",
    "conatct_name": "Piper Cook",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=11",
    "image": "https://source.unsplash.com/random/200x200?sig=14"
  },
  {
    "guid": "092C3BB5-7CDE-CBEC-77B6-BD7974263110",
    "name": "Transportation_to_appointments",
    "phone": "(664) 541-8519",
    "time": "10:31 PM",
    "category": "Health",
    "Priority": "important",
    "isFavorite": false,
    "publisherName": "Gareth Walton",
    "publisherGender": "Male",
    "phone1": "(112) 682-4840",
    "country": "Turkey",
    "date": "2022-08-11 00:02:21",
    "description":
        "arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget,",
    "item_type": "Task",
    "address": "330-3959 Enim Street",
    "location": "720-3243 Fusce St.",
    "conatct_name": "Daphne Beck",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=6",
    "image": "https://source.unsplash.com/random/200x200?sig=11"
  },
  {
    "guid": "69954D0C-998B-07C6-3D4E-4FA8DE787B61",
    "name": "goods,",
    "phone": "1-661-638-6316",
    "time": "5:49 PM",
    "category": "Market",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Vaughan Greer",
    "publisherGender": "Male",
    "phone1": "(489) 517-4816",
    "country": "Norway",
    "date": "2022-08-24 17:57:55",
    "description": "felis, adipiscing fringilla,",
    "item_type": "Task",
    "address": "Ap #160-6642 Id, Rd.",
    "location": "430-7802 Non Avenue",
    "conatct_name": "Roary Barrett",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=7",
    "image": "https://source.unsplash.com/random/200x200?sig=9"
  },
  {
    "guid": "8B6C8AA0-927B-44B7-FC73-CB226071C6BA",
    "name": "Grocery shopping",
    "phone": "(633) 252-1132",
    "time": "3:16 PM",
    "category": "Market",
    "Priority": "important",
    "isFavorite": false,
    "publisherName": "Amanda Bailey",
    "publisherGender": "Male",
    "phone1": "(832) 299-2162",
    "country": "Russian Federation",
    "date": "2022-08-22 21:29:56",
    "description":
        "vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan",
    "item_type": "Task",
    "address": "133-4633 Odio. St.",
    "location": "341 Fringilla Rd.",
    "conatct_name": "Tamara Moore",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=16",
    "image": "https://source.unsplash.com/random/200x200?sig=1"
  },
  {
    "guid": "1C75249B-037D-6673-C582-139B5A34B1C9",
    "name": "Overseeing contractors",
    "phone": "1-896-207-8725",
    "time": "11:02 AM",
    "category": "Health",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Amber Harvey",
    "publisherGender": "Male",
    "phone1": "1-581-576-4558",
    "country": "Sweden",
    "date": "2022-08-15 14:46:38",
    "description": "arcu. Vivamus sit amet risus.",
    "item_type": "Task",
    "address": "Ap #626-1603 Eget Road",
    "location": "289-6799 Mauris. Street",
    "conatct_name": "Hadley Hahn",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=20",
    "image": "https://source.unsplash.com/random/200x200?sig=4"
  },
  {
    "guid": "6F1CD9D2-9724-12FA-A62D-F45245BD47AB",
    "name": "Meal preparation",
    "phone": "1-583-271-6758",
    "time": "11:33 PM",
    "category": "Market",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Shoshana Richard",
    "publisherGender": "Male",
    "phone1": "(762) 349-3253",
    "country": "Ukraine",
    "date": "2022-08-08 10:13:54",
    "description":
        "pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo.",
    "item_type": "Task",
    "address": "256-1684 In, Av.",
    "location": "Ap #811-8170 Ut St.",
    "conatct_name": "Ursa Watts",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=4",
    "image": "https://source.unsplash.com/random/200x200?sig=9"
  },
  {
    "guid": "47AFB2AE-32ED-BD95-6D4D-3CCDA3A3839C",
    "name": "Overseeing contractors",
    "phone": "1-276-547-7444",
    "time": "12:27 PM",
    "category": "Fitness",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Neve Donovan",
    "publisherGender": "Male",
    "phone1": "1-914-847-8347",
    "country": "Canada",
    "date": "2022-08-22 06:01:16",
    "description":
        "nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac,",
    "item_type": "Task",
    "address": "P.O. Box 582, 780 Mollis. Avenue",
    "location": "Ap #287-1394 Erat St.",
    "conatct_name": "Benjamin Guzman",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=6",
    "image": "https://source.unsplash.com/random/200x200?sig=3"
  },
  {
    "guid": "0F554247-C7C2-EA13-6EEB-218FB6B847BC",
    "name": "clothes,",
    "phone": "(955) 578-1097",
    "time": "7:55 AM",
    "category": "Fitness",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Sonya Hammond",
    "publisherGender": "Male",
    "phone1": "(542) 755-6251",
    "country": "Brazil",
    "date": "2022-08-04 03:32:36",
    "description":
        "morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque",
    "item_type": "Task",
    "address": "3560 Est. Rd.",
    "location": "848-4955 Mi. Rd.",
    "conatct_name": "Maya Thomas",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=20",
    "image": "https://source.unsplash.com/random/200x200?sig=18"
  },
  {
    "guid": "C9920EBB-C627-8DF0-3F89-833677FD3C67",
    "name": "Scheduling",
    "phone": "1-254-652-1667",
    "time": "6:20 AM",
    "category": "Fitness",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Rigel Barlow",
    "publisherGender": "Male",
    "phone1": "1-388-545-0432",
    "country": "Brazil",
    "date": "2022-08-06 17:30:22",
    "description":
        "amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu",
    "item_type": "Task",
    "address": "Ap #310-6162 Scelerisque St.",
    "location": "989-2300 Ipsum St.",
    "conatct_name": "Fiona Pierce",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=4",
    "image": "https://source.unsplash.com/random/200x200?sig=17"
  },
  {
    "guid": "737BCCAD-D2BA-C91A-5865-583638EDD890",
    "name": "Phone support",
    "phone": "(107) 861-5125",
    "time": "10:21 AM",
    "category": "Health",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Hunter Hoover",
    "publisherGender": "Male",
    "phone1": "1-411-841-3125",
    "country": "South Africa",
    "date": "2022-08-13 01:48:07",
    "description":
        "augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor",
    "item_type": "Task",
    "address": "873-1452 Quis, Ave",
    "location": "Ap #556-7943 Nec Street",
    "conatct_name": "Maggie Carroll",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=7",
    "image": "https://source.unsplash.com/random/200x200?sig=17"
  },
  {
    "guid": "EE1BF037-51C3-D153-B2ED-DEC2D8394D6E",
    "name": "Paying bills",
    "phone": "1-412-581-8327",
    "time": "3:53 AM",
    "category": "Market",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Orli Shepard",
    "publisherGender": "Male",
    "phone1": "(783) 844-8415",
    "country": "Russian Federation",
    "date": "2022-08-08 06:00:53",
    "description":
        "Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel,",
    "item_type": "Task",
    "address": "P.O. Box 415, 2134 Duis Rd.",
    "location": "P.O. Box 363, 7188 Per Road",
    "conatct_name": "Uriel Gates",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=12",
    "image": "https://source.unsplash.com/random/200x200?sig=20"
  },
  {
    "guid": "8F6FBD10-55CD-2AC7-0BF4-4132E1B52D6E",
    "name": "Grocery shopping",
    "phone": "(968) 685-4814",
    "time": "6:58 PM",
    "category": "Friend",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Bert Phillips",
    "publisherGender": "Male",
    "phone1": "1-578-463-5853",
    "country": "Germany",
    "date": "2022-07-31 01:24:10",
    "description":
        "est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae Donec tincidunt. Donec",
    "item_type": "Task",
    "address": "709-3686 Nisi Rd.",
    "location": "Ap #964-2392 Adipiscing Rd.",
    "conatct_name": "Victor Jones",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=9",
    "image": "https://source.unsplash.com/random/200x200?sig=17"
  },
  {
    "guid": "76A39129-2D81-DA05-96A3-6439420BAC62",
    "name": "Pet care",
    "phone": "(266) 547-7975",
    "time": "6:32 PM",
    "category": "Friend",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Wilma Cote",
    "publisherGender": "Male",
    "phone1": "(404) 643-7622",
    "country": "South Africa",
    "date": "2022-07-27 19:01:34",
    "description":
        "pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et",
    "item_type": "Task",
    "address": "180-6276 Dis Av.",
    "location": "P.O. Box 433, 3308 Donec Av.",
    "conatct_name": "Aimee Gentry",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=5",
    "image": "https://source.unsplash.com/random/200x200?sig=12"
  },
  {
    "guid": "6381C21A-EEB0-6E62-4A74-7E2328D1DE0D",
    "name": "Grocery shopping",
    "phone": "1-757-211-1903",
    "time": "10:00 PM",
    "category": "Health",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Flynn Glass",
    "publisherGender": "Male",
    "phone1": "(721) 544-4252",
    "country": "Norway",
    "date": "2022-08-18 01:55:32",
    "description":
        "turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas.",
    "item_type": "Task",
    "address": "Ap #192-1193 Nec Avenue",
    "location": "493-7570 Vel Street",
    "conatct_name": "Chancellor Sears",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=11",
    "image": "https://source.unsplash.com/random/200x200?sig=12"
  },
  {
    "guid": "26D2B629-4C20-9B95-246C-B2B8BDA16DD6",
    "name": "Research",
    "phone": "(927) 889-3341",
    "time": "7:31 AM",
    "category": "Market",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Miranda Strong",
    "publisherGender": "Male",
    "phone1": "(224) 544-3134",
    "country": "Germany",
    "date": "2022-08-24 15:40:19",
    "description":
        "fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse",
    "item_type": "Task",
    "address": "Ap #721-1676 Ornare, Ave",
    "location": "511-8393 A Av.",
    "conatct_name": "Allen Greer",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=2",
    "image": "https://source.unsplash.com/random/200x200?sig=8"
  },
  {
    "guid": "90478925-C5BB-7C51-BC8E-3B08EA6EDE97",
    "name": "Scheduling appointments",
    "phone": "1-833-601-5225",
    "time": "4:50 AM",
    "category": "Friend",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Bethany Byrd",
    "publisherGender": "Male",
    "phone1": "(147) 716-0831",
    "country": "Chile",
    "date": "2022-08-12 20:41:53",
    "description":
        "scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc",
    "item_type": "Task",
    "address": "925-9420 Sociis Ave",
    "location": "Ap #833-1920 Aliquam Rd.",
    "conatct_name": "Giacomo Ross",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=17",
    "image": "https://source.unsplash.com/random/200x200?sig=10"
  },
  {
    "guid": "DE8C6253-634A-13A4-EBAB-98D475322341",
    "name": "Overseeing contractors",
    "phone": "1-398-224-1970",
    "time": "9:56 AM",
    "category": "Fitness",
    "Priority": "important",
    "isFavorite": false,
    "publisherName": "Ferdinand Mcbride",
    "publisherGender": "Male",
    "phone1": "1-483-718-6527",
    "country": "India",
    "date": "2022-08-17 19:52:20",
    "description":
        "netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat",
    "item_type": "Task",
    "address": "Ap #899-9456 Gravida. Rd.",
    "location": "189-3023 Curabitur Street",
    "conatct_name": "Randall Acosta",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=5",
    "image": "https://source.unsplash.com/random/200x200?sig=2"
  },
  {
    "guid": "BA9395A1-2D9B-246E-B920-72E6B9753AEA",
    "name": "Overseeing contractors",
    "phone": "(264) 743-7361",
    "time": "3:07 PM",
    "category": "Market",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Linus Hancock",
    "publisherGender": "Male",
    "phone1": "(341) 318-1668",
    "country": "Nigeria",
    "date": "2022-08-07 01:08:12",
    "description":
        "elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum",
    "item_type": "Task",
    "address": "956-1503 Orci. Av.",
    "location": "200-4995 Tortor, Street",
    "conatct_name": "Lynn Roy",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=3",
    "image": "https://source.unsplash.com/random/200x200?sig=12"
  },
  {
    "guid": "752662E7-854C-5C84-C174-773CACB21637",
    "name": "clothes,",
    "phone": "(312) 741-8487",
    "time": "9:11 PM",
    "category": "Offical",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Hadley Norman",
    "publisherGender": "Male",
    "phone1": "1-693-233-9340",
    "country": "Austria",
    "date": "2022-08-07 11:59:46",
    "description": "Nulla semper tellus id nunc interdum",
    "item_type": "Task",
    "address": "Ap #297-1878 Felis Street",
    "location": "520-6681 Morbi Avenue",
    "conatct_name": "Cooper Duffy",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=14",
    "image": "https://source.unsplash.com/random/200x200?sig=4"
  },
  {
    "guid": "33886C03-DCF1-C504-3A88-9D76E4A005F4",
    "name": "Light housekeeping",
    "phone": "1-928-823-7800",
    "time": "1:34 PM",
    "category": "Friend",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Phoebe Cole",
    "publisherGender": "Male",
    "phone1": "(657) 658-1111",
    "country": "Russian Federation",
    "date": "2022-08-26 15:42:19",
    "description":
        "venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum",
    "item_type": "Task",
    "address": "P.O. Box 719, 9324 Aenean Ave",
    "location": "Ap #376-4238 Nec, Rd.",
    "conatct_name": "Hyatt Chan",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=13",
    "image": "https://source.unsplash.com/random/200x200?sig=10"
  },
  {
    "guid": "B29830B9-DAFE-D0CA-D168-6D56A4FC4664",
    "name": "Making travel arrangements",
    "phone": "1-601-194-6188",
    "time": "12:24 AM",
    "category": "Offical",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Vielka Shepherd",
    "publisherGender": "Male",
    "phone1": "1-513-376-0263",
    "country": "Australia",
    "date": "2022-08-14 18:23:39",
    "description": "ultricies sem magna",
    "item_type": "Task",
    "address": "Ap #651-5044 Ridiculus Av.",
    "location": "Ap #413-7919 Sem. Rd.",
    "conatct_name": "Alexa Rogers",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=6",
    "image": "https://source.unsplash.com/random/200x200?sig=7"
  },
  {
    "guid": "AD4D035A-D9F5-1C4C-27E0-989C5B97DAB7",
    "name": "Scheduling appointments",
    "phone": "1-354-812-5215",
    "time": "5:12 PM",
    "category": "Market",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Miriam Santiago",
    "publisherGender": "Male",
    "phone1": "(707) 219-1471",
    "country": "Germany",
    "date": "2022-07-28 04:51:06",
    "description":
        "dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida",
    "item_type": "Task",
    "address": "485-660 Sagittis. Ave",
    "location": "823-118 In, Street",
    "conatct_name": "Tashya Guerra",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=9",
    "image": "https://source.unsplash.com/random/200x200?sig=11"
  },
  {
    "guid": "1ED56E50-661F-53BD-D613-E74582AD425E",
    "name": "Research",
    "phone": "1-453-829-6573",
    "time": "9:18 AM",
    "category": "Market",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Adara England",
    "publisherGender": "Male",
    "phone1": "(754) 411-6249",
    "country": "Brazil",
    "date": "2022-08-31 04:31:00",
    "description":
        "a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla",
    "item_type": "Task",
    "address": "379-4579 Pellentesque St.",
    "location": "Ap #361-8550 Urna Rd.",
    "conatct_name": "Tamekah Holman",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=13",
    "image": "https://source.unsplash.com/random/200x200?sig=7"
  },
  {
    "guid": "B5761E1C-D25E-FD8C-2DA4-A2B918EBBCA6",
    "name": "household,",
    "phone": "1-822-525-1757",
    "time": "10:10 PM",
    "category": "Market",
    "Priority": "important",
    "isFavorite": true,
    "publisherName": "Mona Mitchell",
    "publisherGender": "Male",
    "phone1": "(606) 224-2165",
    "country": "New Zealand",
    "date": "2022-08-13 20:33:42",
    "description": "Curabitur massa. Vestibulum accumsan neque",
    "item_type": "Task",
    "address": "629-3295 At Road",
    "location": "396-1203 Elit Rd.",
    "conatct_name": "Ingrid Mccall",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=6",
    "image": "https://source.unsplash.com/random/200x200?sig=19"
  },
  {
    "guid": "9D413591-2E31-D332-DA5C-74AB220E9A52",
    "name": "Phone support",
    "phone": "1-822-457-3631",
    "time": "12:34 AM",
    "category": "Market",
    "Priority": "blue",
    "isFavorite": true,
    "publisherName": "Lesley Gay",
    "publisherGender": "Male",
    "phone1": "(907) 838-5378",
    "country": "Belgium",
    "date": "2022-07-26 10:48:45",
    "description":
        "non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec,",
    "item_type": "Task",
    "address": "4451 Pulvinar St.",
    "location": "P.O. Box 249, 7758 Cum St.",
    "conatct_name": "David Gordon",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=12",
    "image": "https://source.unsplash.com/random/200x200?sig=3"
  },
  {
    "guid": "B9BA7E21-3791-6EF6-F82B-33C232B0E5E1",
    "name": "Pet care",
    "phone": "(122) 615-8366",
    "time": "1:20 AM",
    "category": "Friend",
    "Priority": "blue",
    "isFavorite": true,
    "publisherName": "Keiko Strong",
    "publisherGender": "Male",
    "phone1": "(737) 380-4115",
    "country": "Norway",
    "date": "2022-08-27 05:23:25",
    "description":
        "a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla",
    "item_type": "Task",
    "address": "224-6948 Lectus, Rd.",
    "location": "279-4835 Rutrum Rd.",
    "conatct_name": "Tamara Farmer",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=16",
    "image": "https://source.unsplash.com/random/200x200?sig=13"
  },
  {
    "guid": "C54E15DD-B564-C139-1C94-6234EEE3C22E",
    "name": "Overseeing contractors",
    "phone": "1-732-748-2284",
    "time": "1:32 PM",
    "category": "Market",
    "Priority": "important",
    "isFavorite": true,
    "publisherName": "Hamish Burt",
    "publisherGender": "Male",
    "phone1": "1-389-794-0673",
    "country": "Russian Federation",
    "date": "2022-08-15 14:27:07",
    "description":
        "dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus",
    "item_type": "Task",
    "address": "Ap #481-9348 Augue Road",
    "location": "Ap #606-8549 Ultrices St.",
    "conatct_name": "Finn Good",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=9",
    "image": "https://source.unsplash.com/random/200x200?sig=20"
  },
  {
    "guid": "36812C22-B859-9B5C-5697-F975763C7994",
    "name": "Errands",
    "phone": "(712) 832-3954",
    "time": "3:41 PM",
    "category": "Fitness",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Indigo Davenport",
    "publisherGender": "Male",
    "phone1": "(770) 297-6216",
    "country": "Colombia",
    "date": "2022-08-22 05:28:15",
    "description":
        "Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus,",
    "item_type": "Task",
    "address": "Ap #453-7935 Egestas Rd.",
    "location": "358-3133 Sem, Street",
    "conatct_name": "Kareem Hart",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=20",
    "image": "https://source.unsplash.com/random/200x200?sig=5"
  },
  {
    "guid": "1C6F2AE3-E465-2DD3-C805-5308DEECD572",
    "name": "Emails and correspondence",
    "phone": "1-267-468-8515",
    "time": "5:40 AM",
    "category": "Health",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Daniel Bonner",
    "publisherGender": "Male",
    "phone1": "1-313-374-8664",
    "country": "South Africa",
    "date": "2022-08-22 09:07:53",
    "description":
        "Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue,",
    "item_type": "Task",
    "address": "Ap #540-6727 Dapibus Rd.",
    "location": "Ap #964-3278 Quis Av.",
    "conatct_name": "Stewart Munoz",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=19",
    "image": "https://source.unsplash.com/random/200x200?sig=13"
  },
  {
    "guid": "CBC3A5B6-B4A3-4560-BCA7-354CD8898B35",
    "name": "Overseeing contractors",
    "phone": "(910) 235-7320",
    "time": "11:25 PM",
    "category": "Market",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Brian Franco",
    "publisherGender": "Male",
    "phone1": "(350) 463-5834",
    "country": "Sweden",
    "date": "2022-07-27 16:12:02",
    "description": "eget lacus. Mauris non dui",
    "item_type": "Task",
    "address": "251-8308 Malesuada Av.",
    "location": "978-8941 Phasellus Av.",
    "conatct_name": "Keelie Raymond",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=15",
    "image": "https://source.unsplash.com/random/200x200?sig=1"
  },
  {
    "guid": "65B195EA-68C1-1374-EDC8-A5AFCC5448D0",
    "name": "Taking kids to/from school",
    "phone": "(739) 569-0728",
    "time": "6:10 PM",
    "category": "Health",
    "Priority": "important",
    "isFavorite": false,
    "publisherName": "Lydia Lindsey",
    "publisherGender": "Male",
    "phone1": "(428) 848-4730",
    "country": "Sweden",
    "date": "2022-07-29 12:51:31",
    "description":
        "odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis",
    "item_type": "Task",
    "address": "P.O. Box 360, 9451 Consequat, Ave",
    "location": "Ap #307-9347 Et Road",
    "conatct_name": "Jade Weaver",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=16",
    "image": "https://source.unsplash.com/random/200x200?sig=12"
  },
  {
    "guid": "61426E71-DB29-E8B2-2BB2-359BD5DEF5A5",
    "name": "Taking kids to/from school",
    "phone": "(880) 372-3350",
    "time": "2:35 AM",
    "category": "Market",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Salvador Foley",
    "publisherGender": "Male",
    "phone1": "(363) 834-8673",
    "country": "Chile",
    "date": "2022-08-14 04:18:20",
    "description": "accumsan interdum libero dui",
    "item_type": "Task",
    "address": "473-3985 Ut Av.",
    "location": "Ap #461-7569 Tristique Road",
    "conatct_name": "Abra Pennington",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=18",
    "image": "https://source.unsplash.com/random/200x200?sig=12"
  },
  {
    "guid": "3BB83F26-5441-67A5-C81C-2E3B88677FEE",
    "name": "Light housekeeping",
    "phone": "1-536-212-4755",
    "time": "10:13 PM",
    "category": "Offical",
    "Priority": "important",
    "isFavorite": true,
    "publisherName": "Shaine Hobbs",
    "publisherGender": "Male",
    "phone1": "(668) 418-0892",
    "country": "New Zealand",
    "date": "2022-08-10 03:59:37",
    "description":
        "quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum.",
    "item_type": "Task",
    "address": "Ap #983-7193 Dolor. Avenue",
    "location": "P.O. Box 966, 5100 Adipiscing Rd.",
    "conatct_name": "Patience Mcguire",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=13",
    "image": "https://source.unsplash.com/random/200x200?sig=20"
  },
  {
    "guid": "BD397D78-4678-7C70-C726-D110B4CE731A",
    "name": "Calendar management ",
    "phone": "1-999-638-0048",
    "time": "1:29 PM",
    "category": "Offical",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Nora Marshall",
    "publisherGender": "Male",
    "phone1": "(450) 733-1813",
    "country": "United Kingdom",
    "date": "2022-07-29 22:21:37",
    "description":
        "vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim",
    "item_type": "Task",
    "address": "2009 Non, Road",
    "location": "Ap #528-848 Laoreet, Rd.",
    "conatct_name": "Yolanda Freeman",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=2",
    "image": "https://source.unsplash.com/random/200x200?sig=2"
  },
  {
    "guid": "209D5C4E-6C49-4463-AE87-9B64CD9CAF87",
    "name": "etc.)",
    "phone": "1-154-543-3887",
    "time": "11:54 PM",
    "category": "Offical",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Tyrone Fisher",
    "publisherGender": "Male",
    "phone1": "1-382-365-8855",
    "country": "India",
    "date": "2022-08-13 16:40:53",
    "description": "Donec porttitor tellus non magna. Nam ligula elit, pretium",
    "item_type": "Task",
    "address": "381-8327 Non, Avenue",
    "location": "395-6056 Eget St.",
    "conatct_name": "Daquan William",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=6",
    "image": "https://source.unsplash.com/random/200x200?sig=3"
  },
  {
    "guid": "406B7139-6EC4-4C8A-391D-AC1CEDAD11FC",
    "name": "Research",
    "phone": "1-571-414-4152",
    "time": "11:17 PM",
    "category": "Market",
    "Priority": "important",
    "isFavorite": true,
    "publisherName": "Erasmus Cantrell",
    "publisherGender": "Male",
    "phone1": "(645) 177-1761",
    "country": "Norway",
    "date": "2022-08-24 13:55:40",
    "description": "Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi",
    "item_type": "Task",
    "address": "330-6703 Et, Rd.",
    "location": "1103 Ac St.",
    "conatct_name": "Joshua Dudley",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=2",
    "image": "https://source.unsplash.com/random/200x200?sig=12"
  },
  {
    "guid": "B95FA8B4-5D5F-0E36-8C88-8B56B63455CD",
    "name": "etc.)",
    "phone": "(518) 830-5401",
    "time": "9:20 AM",
    "category": "Fitness",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Lysandra Buck",
    "publisherGender": "Male",
    "phone1": "(174) 737-5738",
    "country": "Ireland",
    "date": "2022-08-14 06:34:05",
    "description":
        "condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor,",
    "item_type": "Task",
    "address": "Ap #375-6600 Turpis. Road",
    "location": "139-6093 Enim. Ave",
    "conatct_name": "Joel Lyons",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=14",
    "image": "https://source.unsplash.com/random/200x200?sig=9"
  },
  {
    "guid": "E26453B2-FC92-81F3-AB9C-DB499066BA2D",
    "name": "Making travel arrangements",
    "phone": "(822) 337-0128",
    "time": "3:51 PM",
    "category": "Friend",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Wylie Jefferson",
    "publisherGender": "Male",
    "phone1": "1-454-616-6962",
    "country": "South Africa",
    "date": "2022-08-15 08:25:02",
    "description":
        "a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis",
    "item_type": "Task",
    "address": "650-4087 Quis, Ave",
    "location": "213-8744 Et, Street",
    "conatct_name": "Isaiah Osborne",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=17",
    "image": "https://source.unsplash.com/random/200x200?sig=2"
  },
  {
    "guid": "94BCAB86-93E1-4F17-5FC6-1D26826A6A39",
    "name": "Overseeing contractors",
    "phone": "1-317-540-5653",
    "time": "11:15 AM",
    "category": "Health",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Amy Craft",
    "publisherGender": "Male",
    "phone1": "(567) 555-2566",
    "country": "Colombia",
    "date": "2022-08-30 21:22:15",
    "description":
        "pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus,",
    "item_type": "Task",
    "address": "Ap #778-9930 Donec Road",
    "location": "P.O. Box 631, 7724 Donec St.",
    "conatct_name": "Ignatius Ferrell",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=20",
    "image": "https://source.unsplash.com/random/200x200?sig=19"
  },
  {
    "guid": "FCAC48EA-4C29-DA0B-D401-E5694EECC561",
    "name": "Phone support",
    "phone": "(827) 281-9152",
    "time": "6:36 AM",
    "category": "Health",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Quamar Lawrence",
    "publisherGender": "Male",
    "phone1": "(654) 833-3454",
    "country": "Sweden",
    "date": "2022-08-08 00:45:51",
    "description":
        "Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt",
    "item_type": "Task",
    "address": "392-3697 Nec Road",
    "location": "P.O. Box 347, 7820 Aliquet, Av.",
    "conatct_name": "Jaquelyn Hoover",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=19",
    "image": "https://source.unsplash.com/random/200x200?sig=14"
  },
  {
    "guid": "4108D5B6-B13A-A569-DB5E-3EC8612E9448",
    "name": "Phone support",
    "phone": "1-381-797-3513",
    "time": "11:34 AM",
    "category": "Friend",
    "Priority": "important",
    "isFavorite": true,
    "publisherName": "Veronica Key",
    "publisherGender": "Male",
    "phone1": "(478) 364-7167",
    "country": "Sweden",
    "date": "2022-08-20 18:01:24",
    "description":
        "nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem",
    "item_type": "Task",
    "address": "8307 Luctus Street",
    "location": "4111 Dictum Road",
    "conatct_name": "Tucker Huffman",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=1",
    "image": "https://source.unsplash.com/random/200x200?sig=10"
  },
  {
    "guid": "E6A13133-9492-4B64-1E4E-2309B946D597",
    "name": "Scheduling",
    "phone": "1-568-968-2446",
    "time": "2:43 PM",
    "category": "Friend",
    "Priority": "important",
    "isFavorite": false,
    "publisherName": "Remedios Olson",
    "publisherGender": "Male",
    "phone1": "(655) 552-1471",
    "country": "New Zealand",
    "date": "2022-07-28 07:05:06",
    "description":
        "Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi",
    "item_type": "Task",
    "address": "2121 Ullamcorper, St.",
    "location": "P.O. Box 269, 2408 Congue Ave",
    "conatct_name": "Amity Coleman",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=8",
    "image": "https://source.unsplash.com/random/200x200?sig=2"
  },
  {
    "guid": "0A6A48D9-5149-D226-954E-4E4577C49BF2",
    "name": "Taking kids to/from school",
    "phone": "(465) 956-2153",
    "time": "2:30 AM",
    "category": "Offical",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Erasmus Salas",
    "publisherGender": "Male",
    "phone1": "1-823-471-2653",
    "country": "China",
    "date": "2022-08-09 20:48:38",
    "description":
        "lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac",
    "item_type": "Task",
    "address": "5466 Congue Avenue",
    "location": "833-4138 Odio. Ave",
    "conatct_name": "Harrison Torres",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=12",
    "image": "https://source.unsplash.com/random/200x200?sig=13"
  },
  {
    "guid": "C0F8543B-AA3C-2331-E9E7-696D41B53C6D",
    "name": "Shopping",
    "phone": "1-314-652-4100",
    "time": "1:52 AM",
    "category": "Friend",
    "Priority": "important",
    "isFavorite": true,
    "publisherName": "Zelda Hopper",
    "publisherGender": "Male",
    "phone1": "1-313-648-2649",
    "country": "Sweden",
    "date": "2022-07-30 19:08:04",
    "description": "odio, auctor vitae, aliquet nec, imperdiet nec, leo.",
    "item_type": "Task",
    "address": "P.O. Box 334, 6705 Eros Road",
    "location": "Ap #558-1086 Ligula. Road",
    "conatct_name": "Lewis Gibbs",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=2",
    "image": "https://source.unsplash.com/random/200x200?sig=11"
  },
  {
    "guid": "394A436A-D41E-ADB4-E3FA-6825CD4B4145",
    "name": "Light garden care",
    "phone": "1-184-101-4360",
    "time": "1:44 AM",
    "category": "Health",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Ulysses Roman",
    "publisherGender": "Male",
    "phone1": "1-602-811-4997",
    "country": "Mexico",
    "date": "2022-08-19 17:40:20",
    "description":
        "accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque.",
    "item_type": "Task",
    "address": "P.O. Box 996, 575 Ultricies St.",
    "location": "831-9490 Nibh. Avenue",
    "conatct_name": "Iona Harper",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=6",
    "image": "https://source.unsplash.com/random/200x200?sig=11"
  },
  {
    "guid": "2D7F235A-2D85-BE87-B8DE-EBC224863B87",
    "name": "clothes,",
    "phone": "1-287-582-3158",
    "time": "6:21 PM",
    "category": "Offical",
    "Priority": "blue",
    "isFavorite": true,
    "publisherName": "Sydney Becker",
    "publisherGender": "Male",
    "phone1": "1-899-352-3632",
    "country": "Germany",
    "date": "2022-07-26 18:45:57",
    "description":
        "orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis",
    "item_type": "Task",
    "address": "Ap #822-3915 Semper St.",
    "location": "6079 Vel Rd.",
    "conatct_name": "Drake Calhoun",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=1",
    "image": "https://source.unsplash.com/random/200x200?sig=6"
  },
  {
    "guid": "32A5C7DA-B987-CFC9-581E-34660FAE0CD9",
    "name": "Taking kids to/from school",
    "phone": "1-178-763-0360",
    "time": "11:49 AM",
    "category": "Health",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Fulton Whitley",
    "publisherGender": "Male",
    "phone1": "(272) 470-9081",
    "country": "South Korea",
    "date": "2022-08-11 10:11:44",
    "description":
        "Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam",
    "item_type": "Task",
    "address": "2860 Purus St.",
    "location": "7909 Amet, Av.",
    "conatct_name": "Janna Clemons",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=12",
    "image": "https://source.unsplash.com/random/200x200?sig=2"
  },
  {
    "guid": "E21AA32C-ADD8-3A5D-7C45-F086AA70E173",
    "name": "Phone support",
    "phone": "1-423-884-7488",
    "time": "12:40 AM",
    "category": "Offical",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Hedwig Pacheco",
    "publisherGender": "Male",
    "phone1": "1-897-125-2420",
    "country": "India",
    "date": "2022-07-29 09:12:54",
    "description":
        "tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi",
    "item_type": "Task",
    "address": "673-3908 Arcu. Av.",
    "location": "P.O. Box 512, 7937 Proin Rd.",
    "conatct_name": "Kerry Webster",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=2",
    "image": "https://source.unsplash.com/random/200x200?sig=14"
  },
  {
    "guid": "4BA1CDC1-E618-F71C-4158-581C163ECAD1",
    "name": "Phone support",
    "phone": "(333) 302-4266",
    "time": "8:46 PM",
    "category": "Market",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Zephania Goff",
    "publisherGender": "Male",
    "phone1": "(863) 836-7858",
    "country": "France",
    "date": "2022-08-15 04:43:41",
    "description":
        "sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit",
    "item_type": "Task",
    "address": "Ap #429-7728 Ornare Avenue",
    "location": "791-8079 Ut Rd.",
    "conatct_name": "Sasha Melendez",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=16",
    "image": "https://source.unsplash.com/random/200x200?sig=18"
  },
  {
    "guid": "E46B5892-1DD6-D7CF-C434-6FB74B7EAC3C",
    "name": "clothes,",
    "phone": "1-338-512-5884",
    "time": "10:18 PM",
    "category": "Friend",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Sade Finch",
    "publisherGender": "Male",
    "phone1": "(851) 642-2254",
    "country": "Austria",
    "date": "2022-08-23 14:48:11",
    "description":
        "Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent",
    "item_type": "Task",
    "address": "611-6523 Massa Avenue",
    "location": "315-556 Diam. Road",
    "conatct_name": "Rogan Bender",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=5",
    "image": "https://source.unsplash.com/random/200x200?sig=19"
  },
  {
    "guid": "675861C9-9924-8614-8BE1-1875463A7622",
    "name": "Shopping",
    "phone": "1-690-324-6277",
    "time": "3:56 AM",
    "category": "Fitness",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Hasad Workman",
    "publisherGender": "Male",
    "phone1": "(697) 622-9409",
    "country": "Sweden",
    "date": "2022-08-24 04:25:47",
    "description":
        "viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi.",
    "item_type": "Task",
    "address": "7373 Egestas Rd.",
    "location": "P.O. Box 428, 5369 Magna. Ave",
    "conatct_name": "Alan Weeks",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=7",
    "image": "https://source.unsplash.com/random/200x200?sig=16"
  },
  {
    "guid": "78BFFAD9-8601-294D-D546-0B9107A98561",
    "name": "household,",
    "phone": "1-541-459-1459",
    "time": "2:30 AM",
    "category": "Market",
    "Priority": "important",
    "isFavorite": false,
    "publisherName": "Cameron Ware",
    "publisherGender": "Male",
    "phone1": "(874) 970-2881",
    "country": "South Korea",
    "date": "2022-07-29 21:28:09",
    "description":
        "rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis",
    "item_type": "Task",
    "address": "P.O. Box 839, 8147 In Road",
    "location": "P.O. Box 590, 6069 Erat Ave",
    "conatct_name": "Kermit Sandoval",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=3",
    "image": "https://source.unsplash.com/random/200x200?sig=11"
  },
  {
    "guid": "318023E5-8776-84D5-1746-6B6A8459BBCC",
    "name": "Taking kids to/from school",
    "phone": "(281) 533-7488",
    "time": "5:18 PM",
    "category": "Market",
    "Priority": "blue",
    "isFavorite": true,
    "publisherName": "Mira Ortega",
    "publisherGender": "Male",
    "phone1": "1-833-880-7751",
    "country": "Poland",
    "date": "2022-08-20 01:06:11",
    "description":
        "ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a,",
    "item_type": "Task",
    "address": "Ap #545-9838 Ipsum. Ave",
    "location": "3845 Faucibus St.",
    "conatct_name": "Griffith Mercer",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=2",
    "image": "https://source.unsplash.com/random/200x200?sig=14"
  },
  {
    "guid": "DE118F88-11D1-716E-371B-7060387ACE5C",
    "name": "Paying bills",
    "phone": "(818) 618-4354",
    "time": "12:41 AM",
    "category": "Health",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Rhiannon Jefferson",
    "publisherGender": "Male",
    "phone1": "1-257-265-4712",
    "country": "Chile",
    "date": "2022-08-20 10:30:06",
    "description":
        "egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id",
    "item_type": "Task",
    "address": "4885 Dis St.",
    "location": "Ap #981-6166 Sit Avenue",
    "conatct_name": "Guy Holden",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=11",
    "image": "https://source.unsplash.com/random/200x200?sig=3"
  },
  {
    "guid": "0273439D-6E6E-CC9D-C5F8-B3895D26A92C",
    "name": "Party planning",
    "phone": "1-983-212-8179",
    "time": "12:36 AM",
    "category": "Health",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Octavia Delgado",
    "publisherGender": "Male",
    "phone1": "1-333-346-6272",
    "country": "South Africa",
    "date": "2022-07-26 18:15:38",
    "description":
        "Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim nisl elementum",
    "item_type": "Task",
    "address": "P.O. Box 421, 1060 Tempus St.",
    "location": "648-1776 Velit Avenue",
    "conatct_name": "Elliott Benjamin",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=16",
    "image": "https://source.unsplash.com/random/200x200?sig=7"
  },
  {
    "guid": "6A92D8DA-42D6-B4DC-BA88-925799B8791B",
    "name": "Overseeing contractors",
    "phone": "1-628-857-2686",
    "time": "7:23 PM",
    "category": "Health",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Idola Hebert",
    "publisherGender": "Male",
    "phone1": "(962) 346-2632",
    "country": "United States",
    "date": "2022-07-25 22:20:25",
    "description":
        "montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis",
    "item_type": "Task",
    "address": "Ap #914-3549 Proin Rd.",
    "location": "225-1015 Ornare. Ave",
    "conatct_name": "Minerva Ford",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=20",
    "image": "https://source.unsplash.com/random/200x200?sig=15"
  },
  {
    "guid": "62F7F5C3-A310-1971-E630-B72C5D8B8BCF",
    "name": "Overseeing contractors",
    "phone": "(644) 243-4402",
    "time": "9:07 PM",
    "category": "Health",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Naida Huber",
    "publisherGender": "Male",
    "phone1": "(322) 377-7752",
    "country": "Poland",
    "date": "2022-08-02 13:40:34",
    "description":
        "sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula.",
    "item_type": "Task",
    "address": "P.O. Box 924, 8619 Nunc St.",
    "location": "Ap #166-2541 Orci Rd.",
    "conatct_name": "Fredericka Henson",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=18",
    "image": "https://source.unsplash.com/random/200x200?sig=8"
  },
  {
    "guid": "A7892B46-EBA2-7387-7372-1181CCB45592",
    "name": "Errands",
    "phone": "1-553-712-4646",
    "time": "8:31 PM",
    "category": "Friend",
    "Priority": "blue",
    "isFavorite": true,
    "publisherName": "Winter Best",
    "publisherGender": "Male",
    "phone1": "1-304-511-6529",
    "country": "South Africa",
    "date": "2022-07-27 04:32:24",
    "description":
        "facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam",
    "item_type": "Task",
    "address": "7133 Leo St.",
    "location": "335-5803 Nonummy Av.",
    "conatct_name": "Hamish Gentry",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=19",
    "image": "https://source.unsplash.com/random/200x200?sig=7"
  },
  {
    "guid": "FA3FF838-1318-78A9-995F-83883F1733B8",
    "name": "Errands",
    "phone": "(302) 237-2712",
    "time": "6:46 AM",
    "category": "Market",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Flynn Jimenez",
    "publisherGender": "Male",
    "phone1": "1-490-545-8289",
    "country": "South Korea",
    "date": "2022-08-18 08:14:32",
    "description":
        "tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae Donec",
    "item_type": "Task",
    "address": "P.O. Box 614, 2010 Maecenas Street",
    "location": "6374 Mus. St.",
    "conatct_name": "Brody Lancaster",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=9",
    "image": "https://source.unsplash.com/random/200x200?sig=6"
  },
  {
    "guid": "10869B39-67CF-8BDD-1607-CCBC4DAD1E1A",
    "name": "Scheduling",
    "phone": "1-225-920-3181",
    "time": "8:30 AM",
    "category": "Market",
    "Priority": "blue",
    "isFavorite": true,
    "publisherName": "Graham Trujillo",
    "publisherGender": "Male",
    "phone1": "(126) 458-9117",
    "country": "United States",
    "date": "2022-08-04 06:40:48",
    "description":
        "montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel",
    "item_type": "Task",
    "address": "P.O. Box 833, 3990 Dui, Ave",
    "location": "Ap #651-4632 Dictum St.",
    "conatct_name": "Linus Marquez",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=6",
    "image": "https://source.unsplash.com/random/200x200?sig=13"
  },
  {
    "guid": "0BDAC35A-7459-3239-B24D-0DB99C5DC175",
    "name": "Transportation_to_appointments",
    "phone": "1-430-560-3873",
    "time": "1:11 AM",
    "category": "Health",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Daria Baxter",
    "publisherGender": "Male",
    "phone1": "(566) 297-2376",
    "country": "Sweden",
    "date": "2022-07-27 02:28:03",
    "description": "metus sit",
    "item_type": "Task",
    "address": "Ap #232-2078 Inceptos St.",
    "location": "379-384 Elementum Rd.",
    "conatct_name": "Holly Sandoval",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=15",
    "image": "https://source.unsplash.com/random/200x200?sig=15"
  },
  {
    "guid": "D3C5AA13-819E-D7AB-8269-4F1119A98836",
    "name": "Paying bills",
    "phone": "(964) 583-5692",
    "time": "9:50 PM",
    "category": "Friend",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Fulton Humphrey",
    "publisherGender": "Male",
    "phone1": "1-648-361-0938",
    "country": "Italy",
    "date": "2022-08-14 08:42:45",
    "description":
        "euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna",
    "item_type": "Task",
    "address": "P.O. Box 539, 7979 Egestas St.",
    "location": "9697 Orci. Ave",
    "conatct_name": "Wang Boone",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=13",
    "image": "https://source.unsplash.com/random/200x200?sig=16"
  },
  {
    "guid": "E92C4A56-B857-16C4-C9A2-0952B5167139",
    "name": "goods,",
    "phone": "1-523-865-1367",
    "time": "1:34 PM",
    "category": "Fitness",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Rafael Snyder",
    "publisherGender": "Male",
    "phone1": "1-534-746-8589",
    "country": "Netherlands",
    "date": "2022-08-03 12:11:01",
    "description":
        "lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi",
    "item_type": "Task",
    "address": "Ap #892-4110 Urna. Ave",
    "location": "P.O. Box 550, 5507 Donec Street",
    "conatct_name": "Rose Jackson",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=14",
    "image": "https://source.unsplash.com/random/200x200?sig=7"
  },
  {
    "guid": "E2D86371-6886-D34A-DA8D-79A2AB75397B",
    "name": "Light housekeeping",
    "phone": "1-236-859-9324",
    "time": "3:48 PM",
    "category": "Market",
    "Priority": "blue",
    "isFavorite": true,
    "publisherName": "Brenda Gallagher",
    "publisherGender": "Male",
    "phone1": "(854) 226-8978",
    "country": "Mexico",
    "date": "2022-08-13 11:00:19",
    "description": "habitant morbi tristique senectus et netus et malesuada",
    "item_type": "Task",
    "address": "P.O. Box 217, 7103 Dui Rd.",
    "location": "600-2100 Amet Road",
    "conatct_name": "Colton Hooper",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=7",
    "image": "https://source.unsplash.com/random/200x200?sig=20"
  },
  {
    "guid": "4B9A55A2-2323-EDD3-29BA-AF3811BAC59B",
    "name": "Light housekeeping",
    "phone": "1-232-985-9268",
    "time": "8:06 PM",
    "category": "Market",
    "Priority": "blue",
    "isFavorite": true,
    "publisherName": "Guinevere Bradford",
    "publisherGender": "Male",
    "phone1": "(471) 487-8659",
    "country": "Mexico",
    "date": "2022-08-26 16:35:44",
    "description":
        "et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras",
    "item_type": "Task",
    "address": "191-8084 Orci, Street",
    "location": "Ap #763-4178 Dui. Ave",
    "conatct_name": "Whilemina Pitts",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=16",
    "image": "https://source.unsplash.com/random/200x200?sig=12"
  },
  {
    "guid": "576AD2F6-95B8-AEE3-BA20-37DA298D5A9B",
    "name": "Shopping",
    "phone": "1-776-553-1466",
    "time": "6:21 PM",
    "category": "Health",
    "Priority": "important",
    "isFavorite": false,
    "publisherName": "Leigh Eaton",
    "publisherGender": "Male",
    "phone1": "(921) 224-6454",
    "country": "Colombia",
    "date": "2022-07-31 17:52:09",
    "description": "ut cursus luctus, ipsum leo elementum sem, vitae aliquam",
    "item_type": "Task",
    "address": "487 Nullam St.",
    "location": "Ap #827-9602 Tellus Road",
    "conatct_name": "Jescie Stafford",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=8",
    "image": "https://source.unsplash.com/random/200x200?sig=5"
  },
  {
    "guid": "3491DB90-73A2-6731-E39F-27B9847A5E4D",
    "name": "household,",
    "phone": "(533) 748-1178",
    "time": "4:02 PM",
    "category": "Friend",
    "Priority": "important",
    "isFavorite": true,
    "publisherName": "Cassandra Boone",
    "publisherGender": "Male",
    "phone1": "(721) 645-5576",
    "country": "Indonesia",
    "date": "2022-08-22 14:07:20",
    "description":
        "consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc",
    "item_type": "Task",
    "address": "Ap #195-4300 Vitae, Ave",
    "location": "P.O. Box 635, 188 Dignissim St.",
    "conatct_name": "Carlos Robbins",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=12",
    "image": "https://source.unsplash.com/random/200x200?sig=5"
  },
  {
    "guid": "4892B209-11E5-A8B9-7F33-4471846D0840",
    "name": "Overseeing contractors",
    "phone": "(149) 882-4680",
    "time": "11:58 AM",
    "category": "Health",
    "Priority": "blue",
    "isFavorite": true,
    "publisherName": "Jillian Jenkins",
    "publisherGender": "Male",
    "phone1": "(286) 515-2753",
    "country": "China",
    "date": "2022-08-14 08:47:03",
    "description":
        "euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget",
    "item_type": "Task",
    "address": "Ap #802-5074 Vestibulum Road",
    "location": "284-3708 Neque St.",
    "conatct_name": "Ross Mcpherson",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=6",
    "image": "https://source.unsplash.com/random/200x200?sig=7"
  },
  {
    "guid": "5822991B-1683-A228-AB6C-D0184202E993",
    "name": "Scheduling",
    "phone": "1-861-400-3888",
    "time": "2:08 AM",
    "category": "Friend",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Driscoll Branch",
    "publisherGender": "Male",
    "phone1": "(977) 286-1361",
    "country": "Austria",
    "date": "2022-08-16 15:39:49",
    "description":
        "sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque",
    "item_type": "Task",
    "address": "590-4707 Hendrerit Street",
    "location": "P.O. Box 767, 2646 Cum Rd.",
    "conatct_name": "Wang Davis",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=19",
    "image": "https://source.unsplash.com/random/200x200?sig=19"
  },
  {
    "guid": "4DE36A37-209A-5DB3-41AE-E27B604E6AD1",
    "name": "Emails and correspondence",
    "phone": "(488) 401-5325",
    "time": "3:53 AM",
    "category": "Friend",
    "Priority": "important",
    "isFavorite": false,
    "publisherName": "Beatrice Middleton",
    "publisherGender": "Male",
    "phone1": "1-884-136-6627",
    "country": "United Kingdom",
    "date": "2022-08-12 13:34:03",
    "description":
        "at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer",
    "item_type": "Task",
    "address": "Ap #260-6813 Lorem Rd.",
    "location": "878-6446 Ac Rd.",
    "conatct_name": "Oprah Johns",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=6",
    "image": "https://source.unsplash.com/random/200x200?sig=3"
  },
  {
    "guid": "BE3C19DF-47E2-86A0-1AE8-4D4511296756",
    "name": "Overseeing contractors",
    "phone": "(460) 261-5317",
    "time": "7:48 PM",
    "category": "Friend",
    "Priority": "important",
    "isFavorite": false,
    "publisherName": "Quinn Whitaker",
    "publisherGender": "Male",
    "phone1": "(253) 707-6625",
    "country": "Austria",
    "date": "2022-08-26 09:11:03",
    "description":
        "in faucibus orci luctus et ultrices posuere cubilia Curae Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat,",
    "item_type": "Task",
    "address": "137-6891 Orci Rd.",
    "location": "7130 Egestas St.",
    "conatct_name": "Colby Little",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=10",
    "image": "https://source.unsplash.com/random/200x200?sig=12"
  },
  {
    "guid": "0BC92C7E-9916-AEF2-C994-B6E4A571E56A",
    "name": "Meal preparation",
    "phone": "1-710-474-0350",
    "time": "2:30 PM",
    "category": "Market",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Ebony Hurst",
    "publisherGender": "Male",
    "phone1": "1-688-201-1255",
    "country": "India",
    "date": "2022-08-02 09:06:15",
    "description": "mattis semper, dui lectus rutrum urna, nec",
    "item_type": "Task",
    "address": "P.O. Box 102, 242 Sociis St.",
    "location": "9804 Neque Rd.",
    "conatct_name": "Nerea Avila",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=16",
    "image": "https://source.unsplash.com/random/200x200?sig=18"
  },
  {
    "guid": "62D655EB-8817-DCA4-9862-AAB64B4ABC29",
    "name": "Pet care",
    "phone": "(755) 511-8064",
    "time": "4:03 AM",
    "category": "Friend",
    "Priority": "orange",
    "isFavorite": true,
    "publisherName": "Uma Gill",
    "publisherGender": "Male",
    "phone1": "(523) 585-7304",
    "country": "India",
    "date": "2022-08-17 18:15:47",
    "description": "rutrum lorem ac risus. Morbi",
    "item_type": "Task",
    "address": "Ap #741-7820 Adipiscing. Avenue",
    "location": "P.O. Box 636, 8486 Malesuada Rd.",
    "conatct_name": "Wing Coleman",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=12",
    "image": "https://source.unsplash.com/random/200x200?sig=9"
  },
  {
    "guid": "2ACD1663-EEAC-DEED-8C43-5A55DB6D8D7C",
    "name": "Making travel arrangements",
    "phone": "1-482-215-0115",
    "time": "11:40 AM",
    "category": "Health",
    "Priority": "important",
    "isFavorite": false,
    "publisherName": "Ray Boyd",
    "publisherGender": "Male",
    "phone1": "(148) 621-2383",
    "country": "Belgium",
    "date": "2022-08-24 07:23:00",
    "description": "auctor, velit eget laoreet posuere, enim nisl elementum",
    "item_type": "Task",
    "address": "748-7063 Nunc Rd.",
    "location": "Ap #870-5648 Fringilla Avenue",
    "conatct_name": "Laith Colon",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=9",
    "image": "https://source.unsplash.com/random/200x200?sig=20"
  },
  {
    "guid": "773B22BF-A87D-E41A-1CA6-919A3C7EC1A0",
    "name": "household,",
    "phone": "(734) 688-7205",
    "time": "1:34 PM",
    "category": "Market",
    "Priority": "important",
    "isFavorite": true,
    "publisherName": "Jordan Leblanc",
    "publisherGender": "Male",
    "phone1": "(842) 376-5564",
    "country": "Norway",
    "date": "2022-08-01 18:22:43",
    "description":
        "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus",
    "item_type": "Task",
    "address": "433-6700 Pretium Rd.",
    "location": "P.O. Box 648, 6679 Iaculis Rd.",
    "conatct_name": "Cedric England",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=6",
    "image": "https://source.unsplash.com/random/200x200?sig=15"
  },
  {
    "guid": "2D1B9ADC-06B3-AFF1-76A3-3B7D0E2ED9BB",
    "name": "Grocery shopping",
    "phone": "1-671-831-8748",
    "time": "4:30 AM",
    "category": "Fitness",
    "Priority": "blue",
    "isFavorite": false,
    "publisherName": "Nelle Dawson",
    "publisherGender": "Male",
    "phone1": "1-152-586-8568",
    "country": "Mexico",
    "date": "2022-08-20 11:02:45",
    "description":
        "vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin",
    "item_type": "Task",
    "address": "Ap #646-6502 Tristique Street",
    "location": "Ap #347-1095 Facilisis Av.",
    "conatct_name": "Peter Floyd",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=17",
    "image": "https://source.unsplash.com/random/200x200?sig=7"
  },
  {
    "guid": "87323EE8-3F24-6378-56D6-B81AA7415242",
    "name": "Light garden care",
    "phone": "(301) 513-8928",
    "time": "5:23 PM",
    "category": "Friend",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Jarrod Alvarez",
    "publisherGender": "Male",
    "phone1": "(309) 537-4939",
    "country": "United Kingdom",
    "date": "2022-08-26 20:21:20",
    "description":
        "cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut",
    "item_type": "Task",
    "address": "278-8026 Bibendum Rd.",
    "location": "Ap #511-3706 Ullamcorper Rd.",
    "conatct_name": "Justina Rosa",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=11",
    "image": "https://source.unsplash.com/random/200x200?sig=20"
  }
];
List doneTasks = [];

List laterTasks = [];
List favoriteTasks = [];
List notifications = [
  {
    "guid": "87323EE8-3F24-6378-56D6-B81AA7415242",
    "name": "Ahmed completed Take bab for a walk",
    "phone": "(301) 513-8928",
    "time": "5:23 PM",
    "category": "Friend",
    "Priority": "orange",
    "isFavorite": false,
    "publisherName": "Jarrod Alvarez",
    "publisherGender": "Male",
    "phone1": "(309) 537-4939",
    "country": "United Kingdom",
    "date": "2022-08-26 20:21:20",
    "description":
        "cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut",
    "item_type": "Task",
    "address": "278-8026 Bibendum Rd.",
    "location": "Ap #511-3706 Ullamcorper Rd.",
    "conatct_name": "Justina Rosa",
    "publisherImage": "https://source.unsplash.com/random/200x200?sig=11",
    "image": "https://source.unsplash.com/random/200x200?sig=20"
  }
];
